version: '3'

services:
  survey:
    build: survey_server/
    depends_on:
      - 'database'
    ports: 
      - '3001:3001'

  results:
    build: results_server/
    depends_on:
      - 'database'
    ports:
      - '3009:3009'

  database:
    image: mysql:latest
